name: "Push new code to github"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'koseproggevent-template-python'

    steps:
      - uses: actions/checkout@v3
      - run: cd src && zip -r index.zip .
      - name: Deploy source code
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"
          GROUP_NAME: ${{ github.event.repository.name }}
        run: GROUP=$(echo $GROUP_NAME | cut -d '-' -f 1) && aws s3 cp src/index.zip s3://koseproggevent-lambda-deployments/deployments/$GROUP/index.zip
